import { NgModule } from '@angular/core';
import {
  TuiAlertModule, TuiButtonModule,
  TuiDialogModule, TuiErrorModule, TuiExpandModule, TuiGroupModule, TuiHintModule, TuiHostedDropdownModule,
  TuiModeModule,
  TuiRootModule, TuiScrollbarModule,
  TuiSvgModule, TuiTextfieldControllerModule,
  TuiThemeNightModule,
  TuiPrimitiveTextfieldModule
} from "@taiga-ui/core";
import {TuiBlockStatusModule} from "@taiga-ui/layout";
import {
  TuiActionModule, TuiCarouselModule, TuiDataListWrapperModule, TuiFieldErrorPipeModule,
  TuiInputModule, TuiInputNumberModule, TuiInputPasswordModule,
  TuiInputTagModule, TuiIslandModule, TuiMultiSelectModule,
  TuiProgressModule,
  TuiRoutableDialogModule, TuiSelectModule,
  TuiTagModule,
  TuiTextareaModule
} from "@taiga-ui/kit";



@NgModule({
  declarations: [],
  imports: [
    TuiRootModule,
    TuiDialogModule,
    TuiAlertModule,
    TuiThemeNightModule,
    TuiPrimitiveTextfieldModule,
    TuiModeModule,
    TuiSvgModule,
    TuiBlockStatusModule,
    TuiTagModule,
    TuiButtonModule,
    TuiActionModule,
    TuiRoutableDialogModule,
    TuiInputModule,
    TuiInputTagModule,
    TuiTextfieldControllerModule,
    TuiHostedDropdownModule,
    TuiExpandModule,
    TuiTextareaModule,
    TuiErrorModule,
    TuiHintModule,
    TuiInputPasswordModule,
    TuiCarouselModule,
    TuiIslandModule,
    TuiScrollbarModule,
    TuiFieldErrorPipeModule,
    TuiGroupModule,
    TuiSelectModule,
    TuiDataListWrapperModule,
    TuiMultiSelectModule,
    TuiInputNumberModule,
    TuiProgressModule,
  ],
  exports: [
    TuiRootModule,
    TuiDialogModule,
    TuiAlertModule,
    TuiThemeNightModule,
    TuiPrimitiveTextfieldModule,
    TuiModeModule,
    TuiSvgModule,
    TuiBlockStatusModule,
    TuiTagModule,
    TuiButtonModule,
    TuiActionModule,
    TuiRoutableDialogModule,
    TuiInputModule,
    TuiInputTagModule,
    TuiTextfieldControllerModule,
    TuiHostedDropdownModule,
    TuiExpandModule,
    TuiTextareaModule,
    TuiErrorModule,
    TuiHintModule,
    TuiInputPasswordModule,
    TuiCarouselModule,
    TuiIslandModule,
    TuiScrollbarModule,
    TuiFieldErrorPipeModule,
    TuiGroupModule,
    TuiSelectModule,
    TuiDataListWrapperModule,
    TuiMultiSelectModule,
    TuiInputNumberModule,
    TuiProgressModule,
  ]
})
export class TuiSharedModuleModule { }
